[package]
name = "guest_code_for_zk_proof"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "1", default-features = false, features = ["std"] }
ed25519-dalek = "2"
common = { path = "../../common" }

